---
##################################################
# 実行するタスクを定義する
##################################################

- name: CentOS用の設定
  include: centos.yml
  when: ansible_os_family == "RedHat"
  tags:
    - redis

- name: Ubuntu用の設定
  include: ubuntu.yml
  when: ansible_os_family == "Debian"
  tags:
    - redis
