---
##################################################
# Define tasks
##################################################

- name: Install repository of nginx
  copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
  become: yes # use sudo

- name: Install Nginx
  yum:
    name: nginx
    state: present
  become: yes # use sudo

- name: Start nginx and Enable autostart
  systemd:
    name: nginx
    state: started
    enabled: yes
  become: yes # use sudo
