---
##################################################
# Define tasks
##################################################

- name: Install repository of MongoDB
  copy:
    src: mongodb-org-4.0.repo
    dest: /etc/yum.repos.d/mongodb-org-4.0.repo
  become: yes # use sudo

- name: Install MongoDB
  yum:
    name: mongodb-org
    state: latest
    update_cache: yes
  become: yes # use sudo
