---
##################################################
# Define tasks
##################################################

- name: laravelがセットアップ済みか確認
  stat:
    path: /var/www/html/laravelapp/artisan
    get_checksum: false
    get_md5: false
  register: is_laravel_folder
  become: yes
  become_user: "{{ app_own_user }}"

- name: Laravel Installerのインストール
  composer:
    command: require
    global_command: yes
    arguments: laravel/installer=~1.1
  become: yes
  become_user: "{{ app_own_user }}"
  when: is_laravel_folder.stat.exists == False

- name: laravelのセットアップ
  shell: |
    cd /var/www/html/laravelapp
    ~/.config/composer/vendor/bin/laravel new
    chmod +w storage bootstrap/cache
  become: yes
  become_user: "{{ app_own_user }}"
  when: is_laravel_folder.stat.exists == False

- name: PHP Coding Standards Fixer
  composer:
    command: require
    no-dev: yes
    arguments: friendsofphp/php-cs-fixer
    working_dir: /var/www/html/laravelapp
  become: yes
  become_user: "{{ app_own_user }}"

- name: PHP_CodeSniffer
  composer:
    command: require
    no-dev: yes
    arguments: squizlabs/php_codesniffer
    working_dir: /var/www/html/laravelapp
  become: yes
  become_user: "{{ app_own_user }}"

- name: PHP Mess Detector
  composer:
    command: require
    no-dev: yes
    arguments: phpmd/phpmd=@stable
    working_dir: /var/www/html/laravelapp
  become: yes
  become_user: "{{ app_own_user }}"

- name: Install Horizon
  composer:
    command: require
    arguments: laravel/horizon
    working_dir: /var/www/html/laravelapp
  become: yes
  become_user: "{{ app_own_user }}"

- name: Install laravel-mix
  yarn:
    path: /var/www/html/laravelapp
  become: yes

- name: Install laravel-debugbar
  composer:
    command: require
    no-dev: yes
    arguments: barryvdh/laravel-debugbar
    working_dir: /var/www/html/laravelapp
  become: yes
  become_user: "{{ app_own_user }}"

- name: Install laravel helper
  composer:
    command: require
    no-dev: yes
    arguments: barryvdh/laravel-ide-helper
    working_dir: /var/www/html/laravelapp
  become: yes
  become_user: "{{ app_own_user }}"

- name: create helper file
  shell: |
    php artisan ide-helper:generate
  args:
    chdir: /var/www/html/laravelapp
  become: yes
  become_user: "{{ app_own_user }}"

- name: Install Laravel Telescope
  composer:
    command: require
    no-dev: yes
    arguments: laravel/telescope
    working_dir: /var/www/html/laravelapp
  become: yes
  become_user: "{{ app_own_user }}"

- name: アセットの公開
  shell: |
    php artisan telescope:install
    php artisan migrate
  args:
    chdir: /var/www/html/laravelapp
  become: yes
  become_user: "{{ app_own_user }}"

- name: Install predis
  composer:
    command: require
    no-dev: yes
    arguments: predis/predis
    working_dir: /var/www/html/laravelapp
  become: yes
  become_user: "{{ app_own_user }}"

- name: フォルダ権限の変更
  shell: |
    chown -R apache:apache /var/www/html/laravelapp
  become: yes
