---
##################################################
# Define tasks
##################################################

- name: Create Database
  mysql_db:
    name: "{{ app_db }}"
    state: present
  become: yes # use sudo

- name: DBユーザーを作成し，アプリケーションで使用するDBのすべての権限を与える
  mysql_user:
    name: "{{ app_db_user }}"
    password: "{{ app_db_password }}"
    priv: "{{ app_db_user }}.*:ALL,GRANT"
    host: localhost
    state: present
  become: yes # use sudo

- name: set mysql_native_password
  command: mysql --user root --password={{ mysql_root_db_pass }} --connect-expired-password --execute="ALTER USER '{{ app_db_user }}'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ app_db_password }}';"