---
##################################################
# Define tasks
##################################################

- name: laravelがセットアップ済みか確認
  stat:
    path: "{{ document_root }}/artisan"
    get_checksum: false
    get_md5: false
  register: is_laravel_folder
  become: yes
  become_user: "{{ app_own_user }}"
  tags:
    - laravel

- name: Laravel Installerのインストール
  composer:
    command: require
    global_command: yes
    arguments: laravel/installer
  become: yes
  become_user: "{{ app_own_user }}"
  when: not is_laravel_folder.stat.exists
  tags:
    - laravel

- name: laravelのセットアップ
  shell: |
    ~/.composer/vendor/bin/laravel new
    chmod +w storage bootstrap/cache
  args:
    chdir: "{{ document_root }}"
    warn: false
  become: yes
  become_user: "{{ app_own_user }}"
  when: not is_laravel_folder.stat.exists
  tags:
    - laravel

- name: Composer update
  composer:
    command: update
    working_dir: "{{ document_root }}"
  become: yes
  become_user: "{{ app_own_user }}"
  tags:
    - laravel

- name: Copy .env to server's directory
  template:
    src: .env.j2
    dest: "{{ document_root }}/.env"
    owner: "{{ app_own_user }}"
    group: "{{ app_own_user }}"
    mode: 0644
  tags:
    - laravel

- name: laravelのセットアップ2
  shell: |
    cp -a .env.example .env
    php artisan key:generate
  args:
    chdir: "{{ document_root }}"
    warn: false
  become: yes
  become_user: "{{ app_own_user }}"
  when: not is_laravel_folder.stat.exists
  tags:
    - laravel

- name: PHP Coding Standards Fixer
  composer:
    command: require
    no-dev: yes
    arguments: friendsofphp/php-cs-fixer
    working_dir: "{{ document_root }}"
  become: yes
  become_user: "{{ app_own_user }}"
  when: app_plugin.isPhpCs
  tags:
    - laravel

- name: PHP_CodeSniffer
  composer:
    command: require
    no-dev: yes
    arguments: squizlabs/php_codesniffer
    working_dir: "{{ document_root }}"
  become: yes
  become_user: "{{ app_own_user }}"
  when: app_plugin.isPhpCsniffer
  tags:
    - laravel

- name: PHP Mess Detector
  composer:
    command: require
    no-dev: yes
    arguments: phpmd/phpmd=@stable
    working_dir: "{{ document_root }}"
  become: yes
  become_user: "{{ app_own_user }}"
  when: app_plugin.isPhpmd
  tags:
    - laravel

- name: Install Horizon
  composer:
    command: require
    arguments: laravel/horizon
    working_dir: "{{ document_root }}"
  become: yes
  become_user: "{{ app_own_user }}"
  when: app_plugin.isHorizon
  tags:
    - laravel

- name: Install laravel-mix
  shell: |
    yarn install
  args:
    chdir: "{{ document_root }}"
  become: yes
  when: app_plugin.isLaravelMix
  tags:
    - laravel

- name: Install laravel-debugbar
  composer:
    command: require
    no-dev: yes
    arguments: barryvdh/laravel-debugbar
    working_dir: "{{ document_root }}"
  become: yes
  become_user: "{{ app_own_user }}"
  when: app_plugin.isLaravelDebugbar
  tags:
    - laravel

- name: Install laravel helper
  composer:
    command: require
    no-dev: yes
    arguments: barryvdh/laravel-ide-helper
    working_dir: "{{ document_root }}"
  become: yes
  become_user: "{{ app_own_user }}"
  when: app_plugin.isIdeHeloper
  tags:
    - laravel

- name: create helper file
  command: php artisan ide-helper:generate
  args:
    chdir: "{{ document_root }}"
  become: yes
  become_user: "{{ app_own_user }}"
  when: app_plugin.isIdeHeloper
  tags:
    - laravel

- name: Install Laravel Telescope
  composer:
    command: require
    no-dev: yes
    arguments: laravel/telescope
    working_dir: "{{ document_root }}"
  become: yes
  become_user: "{{ app_own_user }}"
  when: app_plugin.isLaravelTelescope
  tags:
    - laravel

- name: アセットの公開
  shell: |
    php artisan telescope:install
    php artisan migrate
  args:
    chdir: "{{ document_root }}"
  become: yes
  become_user: "{{ app_own_user }}"
  tags:
    - laravel

- name: Install predis
  composer:
    command: require
    no-dev: yes
    arguments: predis/predis
    working_dir: "{{ document_root }}"
  become: yes
  become_user: "{{ app_own_user }}"
  when: app_plugin.isPredis
  tags:
    - laravel

- name: Generate a key
  command: php artisan key:generate
  args:
    chdir: "{{ document_root }}"
  become: yes
  become_user: "{{ app_own_user }}"
  tags:
    - laravel

- name: フォルダ権限の変更
  file:
    path: "{{ document_root }}"
    owner: www-data
    group: www-data
  become: yes
  tags:
    - laravel

