---
##################################################
# Define tasks
##################################################

- name: Install apache
  apt:
    name:
      - apache2
    state: present
  become: yes # use sudo

- name: Copy apache2.conf to server's directory
  template:
    src: ubuntu/apache2.conf.j2
    dest: /etc/apache2/apache2.conf
    owner: root
    group: root
    mode: 0644
  become: yes # use sudo
  notify:
    - restart_apache_debian

- name: Copy vhosts.conf to server's directory
  template:
    src: ubuntu/000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
    owner: root
    group: root
    mode: 0644
  become: yes # use sudo
  notify:
    - restart_apache_debian

- name: Start apache and Enable autostart
  systemd:
    name: apache2
    state: started
    enabled: yes
  become: yes # use sudo
