---
##################################################
# Define tasks
##################################################

- name: Install apache
  apt:
    name: apache2
    state: present

- name: Copy apache2.conf to server's directory
  template:
    src: ubuntu/apache2.conf.j2
    dest: /etc/apache2/apache2.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_apache_debian

- name: Copy vhosts.conf to server's directory
  template:
    src: ubuntu/000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_apache_debian

- name: Enable mod_rewrite
  shell: |
    a2enmod rewrite
    systemctl restart apache2
  notify:
    - restart_apache_debian

- name: Start apache and Enable autostart
  systemd:
    name: apache2
    state: started
    enabled: yes
