---
##################################################
# 変数のデフォルト値を定義する
##################################################

# rootユーザのパスワード
mysql_root_password: secret

# homesteadユーザのパスワード
mysql_db_password: secret
