---
##################################################
# Define tasks
##################################################

- name: Install repository of MariaDB
  shell: |
    set -o pipefail
    curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | sudo bash
  become: yes # use sudo

- name: Install MariaDB
  apt:
    name:
      - libmysqlclient-dev
      - mariadb-client
      - mariadb-server
      - python
      - python-pip
      - python-setuptools
    state: present
    update_cache: yes
  become: yes # use sudo

- name: Install MySQL-python
  pip:
    name: MySQL-python
  become: yes # use sudo

- name: Copy my.cnf template
  template:
    src: my.cnf.ubuntu.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644
  become: yes # use sudo
  notify:
    - restart_mariadb

- name: Enable MariaDB service
  systemd:
    name: mariadb
    state: started
    enabled: yes
  become: yes # use sudo

- name: Set root's password
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
  become: yes # use sudo

- name: Copy .my.cnf template
  template:
    src: my.client.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0644
  become: yes # use sudo
