---
##################################################
# Define tasks
##################################################

- name: Remove a installed mariadb
  yum:
    name: mariadb-libs
    state: removed

- name: Install a repository
  yum:
    name: "{{ mysql_repository }}"
    state: present

- name: Install MySQLDB
  yum:
    name: "{{ mysql_pkgs }}"
    state: present

- name: Enable MySQLDB service
  systemd:
    name: "{{ mysql_service }}"
    state: restarted
    enabled: yes

- name: get root password
  shell: "grep 'A temporary password is generated for root@localhost' /var/log/mysqld.log | awk -F ' ' '{print $(NF)}'"
  register: root_password

- name: update expired root user password
  command: >
    mysql
    --user root
    --password={{ root_password.stdout }}
    --connect-expired-password
    --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_db_pass }}';"

- name: set mysql_native_password
  command: >
    mysql
    --user root
    --password={{ mysql_root_db_pass }}
    --connect-expired-password
    --execute="ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_db_pass }}';"

# - name: Set root's password
#   mysql_user:
#     name: root
#     host: localhost
#     password: "{{ mysql_root_db_pass }}"

- name: Copy my.cnf template
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_mysqld

- name: Copy .my.cnf template
  template:
    src: my.client.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_mysqld
