---
##################################################
# Define tasks
##################################################

- name: Register NodeJS repository
  shell: |
    curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
  become: yes # use sudo

- name: Install NodeJS
  yum:
    name: nodejs
    state: latest
  become: yes # use sudo

- name: Register Yarn repository
  shell: |
    curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
  become: yes # use sudo

- name: Install Yarn
  yum:
    name: yarn
    state: latest
  become: yes # use sudo
