---
##################################################
# 変数のデフォルト値を定義する
##################################################

# 開発モード
is_development: true

# Apacheのドキュメントルート
# Virtual Hostで実装
apache_document_root: /var/www/html/public
apache_server_name: web.devops
