---
##################################################
# Define tasks
##################################################

- name: Install EPEL repository
  yum:
    name: epel-release
    state: latest
  become: yes # use sudo

- name: Install Remi repository
  yum:
    name: "http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    state: present
  become: yes # use sudo

- name: Install PHP
  yum:
    name:
      - php
      - php-bcmath
      - php-cli
      - php-common
      - php-devel
      - php-json
      - php-mcrypt
      - php-mbstring
      - php-mysqlnd
      - php-opcache
      - php-openssl
      - php-pdo
      - php-pear
      - php-pecl-memcache
      - php-pecl-memcached
      - php-pecl-zip
      - php-pgsql
      - php-process
      - php-tokenizer
      - php-xml
    state: present
    enablerepo: remi,remi-php72
  become: yes # use sudo
  notify:
    - restart_apache_redhat

- name: Copy custom php.ini
  copy:
    src: zzmyphp.ini
    dest: /etc/php.d/zzmyphp.ini
  become: yes # use sudo
  notify:
    - restart_apache_redhat

- name: Install Composer
  shell: |
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer creates=/usr/bin/composer
  become: yes # use sudo

