---
##################################################
# Define tasks
##################################################

- name: Install PHP
  apt:
    name:
      - php7.2
      - libapache2-mod-php7.2
      - php7.2-bcmath
      - php7.2-cli
      - php7.2-common
      - php7.2-dev
      - php7.2-json
      - php7.2-mbstring
      - php7.2-mysqlnd
      - php7.2-opcache
      #      - php7.2-openssl
      - php7.2-pdo
      - php-pear
      - php7.2-pgsql
      #      - php7.2-process
      - php7.2-tokenizer
      - php7.2-xml
    state: latest
  become: yes # use sudo

- name: Install Composer
  shell: |
    curl -sS https://getcomposer.org/installer
    php -- --install-dir=/usr/bin --filename=composer creates=/usr/bin/composer
  become: yes # use sudo
