---
##################################################
# Define tasks
##################################################

- name: Install related packages
  yum:
    name:
      - libevent-devel
      - perl-core
      - perl-CPAN
      - perl-Test-Harness
    state: latest
  become: yes # use sudo

- name: Set CPAN Configuration
  shell: |
    (echo y;echo o conf prerequisites_policy follow;echo o conf commit) | cpan
  become: yes # use sudo

- name: Install perl modules
  shell: |
    perl -MCPAN -e 'CPAN::Shell->install("Test::More")'
  become: yes # use sudo

- name: Download file with check (sha256)
  get_url:
    url: "https://www.memcached.org/files/{{ version }}.tar.gz"
    dest: /usr/local/src/
    checksum: "{{ checksum }}"
  become: yes # use sudo

- name: Install memcached
  shell: |
    tar -zxvf "{{ version }}.tar.gz"
    cd "{{ version }}"
    ./configure --prefix=/usr/local/memcached
    make && make test && make install
  args:
    chdir: /usr/local/src/
  become: yes # use sudo

